### ISSUE TITLE
batch 新增的 MLE 部分偶然发现了运行时错误

### ISSUE THREAD

**Issue by Berrysoft** [heroxbd/waveform-analysis#140]
```
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/home/ubuntu/waveform-analysis/batch.py", line 334, in get_t0
    t0_l[i - a0], mu_l[i - a0] = wff.fit_t0mu_gibbs(loc_i, t00_list, step, tau, sigma, mu_t, t00, b_mu, b_t0, TRIALS)                                                                                                                                         File "/home/ubuntu/waveform-analysis/wf_func.py", line 443, in fit_t0mu_gibbs
    fval = np.array([t_t0(t_i) for t_i in t0_list])
  File "/home/ubuntu/waveform-analysis/wf_func.py", line 443, in <listcomp>
    fval = np.array([t_t0(t_i) for t_i in t0_list])
  File "/home/ubuntu/waveform-analysis/wf_func.py", line 434, in t_t0
    ans = opti.fmin_l_bfgs_b(lambda μ: μ - special.logsumexp(NPE * np.log(μ / mu) + f_agg),
  File "/usr/lib/python3/dist-packages/scipy/optimize/lbfgsb.py", line 197, in fmin_l_bfgs_b
    res = _minimize_lbfgsb(fun, x0, args=args, jac=jac, bounds=bounds,
  File "/usr/lib/python3/dist-packages/scipy/optimize/lbfgsb.py", line 306, in _minimize_lbfgsb
    sf = _prepare_scalar_function(fun, x0, jac=jac, args=args, epsilon=eps,
  File "/usr/lib/python3/dist-packages/scipy/optimize/optimize.py", line 261, in _prepare_scalar_function
    sf = ScalarFunction(fun, x0, args, grad, hess,
  File "/usr/lib/python3/dist-packages/scipy/optimize/_differentiable_functions.py", line 136, in __init__                                                                                                                                                      self._update_fun()
  File "/usr/lib/python3/dist-packages/scipy/optimize/_differentiable_functions.py", line 226, in _update_fun                                                                                                                                                   self._update_fun_impl()
  File "/usr/lib/python3/dist-packages/scipy/optimize/_differentiable_functions.py", line 133, in update_fun                                                                                                                                                    self.f = fun_wrapped(self.x)
  File "/usr/lib/python3/dist-packages/scipy/optimize/_differentiable_functions.py", line 130, in fun_wrapped                                                                                                                                                   return fun(x, *args)
  File "/home/ubuntu/waveform-analysis/wf_func.py", line 434, in <lambda>
    ans = opti.fmin_l_bfgs_b(lambda μ: μ - special.logsumexp(NPE * np.log(μ / mu) + f_agg),
  File "/usr/lib/python3/dist-packages/scipy/special/_logsumexp.py", line 99, in logsumexp
    a_max = np.amax(a, axis=axis, keepdims=True)
  File "<__array_function__ internals>", line 5, in amax
  File "/usr/lib/python3/dist-packages/numpy/core/fromnumeric.py", line 2705, in amax
    return _wrapreduction(a, np.maximum, 'max', axis, None, out,
  File "/usr/lib/python3/dist-packages/numpy/core/fromnumeric.py", line 87, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation maximum which has no identity
```

**Comment by heroxbd** [comment]
@dachengx 查明原因

**Comment by dachengx** [comment]
首先这不一定是 MLE 的错误。以及我会查明原因。

**Comment by Berrysoft** [comment]
**相同**的文件在 `collect.py` 也出错了：
```
9921 waveforms are computed
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/home/ubuntu/waveform-analysis/collect.py", line 89, in collect
    pet, cha = wff.clip(pet, cha, 0.0)
  File "/home/ubuntu/waveform-analysis/wf_func.py", line 561, in clip
    pet = np.array([pet[np.argmax(cha)]])
  File "<__array_function__ internals>", line 5, in argmax
  File "/usr/lib/python3/dist-packages/numpy/core/fromnumeric.py", line 1188, in argmax
    return _wrapfunc(a, 'argmax', axis=axis, out=out)
  File "/usr/lib/python3/dist-packages/numpy/core/fromnumeric.py", line 58, in _wrapfunc
    return bound(*args, **kwds)
ValueError: attempt to get argmax of an empty sequence
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/waveform-analysis/collect.py", line 119, in <module>
    result = pool.starmap(partial(collect), slices)
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
ValueError: attempt to get argmax of an empty sequence
```

**Comment by Berrysoft** [comment]
附上 `batch.py` 的更改：
``` diff
diff --git a/batch.py b/batch.py
index 451016f..a03fa22 100644
--- a/batch.py
+++ b/batch.py
@@ -21,7 +21,7 @@ psr.add_argument("-o", dest="opt", type=str, help="output file")
 psr.add_argument("ipt", type=str, help="input file")
 psr.add_argument("--ref", type=str, help="truth file")
 psr.add_argument("--size", type=int, default=100, help="batch size")
-psr.add_argument('-N', '--Ncpu', dest='Ncpu', type=int, default=50)
+psr.add_argument('-N', '--Ncpu', dest='Ncpu', type=int, default=4)
 args = psr.parse_args()

 fipt = args.ipt
@@ -402,7 +402,7 @@ for part in range(l_e // args.size + 1):
                    tq[i_part, :lp_t],
                    np.append(s[i_part, :lp_NPE], s_null, axis=1),
                    cp.asarray(z[i_part, :lp_wave], np.float32))
-        t0, mu = get_t0_pool(s0_history, t0_history, loc, flip, index[i_part], tq[i_part, :lp_t], start['T0'][i_part])
+        #t0, mu = get_t0_pool(s0_history, t0_history, loc, flip, index[i_part], tq[i_part, :lp_t], start['T0'][i_part])
         fi_part = (i_part * TRIALS)[:, None] + np.arange(TRIALS)[None, :]
         fip = fi_part.flatten()
         sample["flip"][fip] = flip.flatten()
@@ -415,8 +415,8 @@ for part in range(l_e // args.size + 1):
         min_col = min(last_max_s.shape[1], index['l_t'].max())
         s_max["s_max"][i_part, :min_col] = last_max_s[:, :min_col]
         s_max["consumption"][i_part] = (time.time() - time_start) / l_part
-        s_max["t0"][i_part] = t0
-        s_max["mu"][i_part] = mu
+        #s_max["t0"][i_part] = t0
+        #s_max["mu"][i_part] = mu
 print(f"FSMP finished, real time {s_max['consumption'].sum():.02f}s")

 with h5py.File(fopt, "w") as opt:
```

**Comment by dachengx** [comment]
`bat:/tmp/0.5-20-5.h5` 中某一条波形的采样结果中 NPE 全是 0，导致了报错
